python src/main.py --config=qmix --env-config=grid_prey5
python src/main.py --config=qmix --env-config=grid_prey7
python src/main.py --config=vdn --env-config=grid_prey5
python src/main.py --config=vdn --env-config=grid_prey7
python src/main.py --config=qtran --env-config=grid_prey5
python src/main.py --config=qtran --env-config=grid_prey7
python src/main.py --config=qmix --env-config=grid
python src/main.py --config=qmix --env-config=grid_spread
python src/main.py --config=vdn --env-config=grid
python src/main.py --config=vdn --env-config=grid_spread
