python src/main.py --config=coma --env-config=grid_prey5
python src/main.py --config=coma --env-config=grid_prey7
python src/main.py --config=iql --env-config=grid_prey5
python src/main.py --config=iql --env-config=grid_prey7
python src/main.py --config=coma --env-config=grid
python src/main.py --config=coma --env-config=grid_spread
python src/main.py --config=iql --env-config=grid
python src/main.py --config=iql --env-config=grid_spread
python src/main.py --config=qtran --env-config=grid
python src/main.py --config=qtran --env-config=grid_spread
